# Generated by Django 3.2.5 on 2022-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='additional_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='useringredient',
            name='portion',
            field=models.FloatField(default=1),
        ),
    ]
