# Generated by Django 3.2.5 on 2022-05-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0003_alter_useringredient_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredient',
            name='additional_cost',
        ),
        migrations.RemoveField(
            model_name='useringredient',
            name='portion',
        ),
    ]
