# Generated by Django 3.2.5 on 2022-05-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0004_auto_20220529_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
