# Generated by Django 3.2.5 on 2022-05-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('rrs_app', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='useringredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='useringredient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
