# Generated by Django 3.2.5 on 2022-06-21 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrs_app', '0011_alter_useringredient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addcost', models.FloatField(default=0)),
                ('portion', models.FloatField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
