# Generated by Django 3.2.5 on 2022-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0012_auto_20220621_1312'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipeingredient'),
        ),
        migrations.AddConstraint(
            model_name='useringredient',
            constraint=models.UniqueConstraint(fields=('user', 'ingredient'), name='unique_useringredient'),
        ),
    ]
