# Generated by Django 3.2.5 on 2022-06-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0014_auto_20220622_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='useringredient',
            unique_together=set(),
        ),
    ]
