# Generated by Django 3.2.5 on 2022-06-22 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrs_app', '0015_auto_20220622_1626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='useringredient',
            unique_together={('user', 'ingredient')},
        ),
    ]
