# Generated by Django 3.2.5 on 2022-06-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0016_auto_20220622_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
