# Generated by Django 3.2.5 on 2022-06-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0021_alter_useringredient_total_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('title',)},
        ),
    ]
