# Generated by Django 3.2.5 on 2022-06-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0022_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('title',)},
        ),
    ]
