# Generated by Django 3.2.5 on 2022-06-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0023_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useringredient',
            options={'ordering': ('user', 'ingredient')},
        ),
    ]
