# Generated by Django 3.2.5 on 2022-06-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0024_alter_useringredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('recipe', 'ingredient')},
        ),
    ]
