# Generated by Django 3.2.5 on 2022-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0025_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='total_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ImageField(null=True, upload_to='ingredient_photos/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(null=True, upload_to='recipe_photos/'),
        ),
    ]
