# Generated by Django 3.2.5 on 2022-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0026_auto_20220703_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useringredient',
            old_name='total_cost',
            new_name='add_cost',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='recipe',
            name='add_cost',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
