# Generated by Django 3.2.5 on 2022-07-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0027_auto_20220703_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='add_cost',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='useringredient',
            old_name='add_cost',
            new_name='total_cost',
        ),
    ]
